
#pragma once
#include <Arduino.h>
#include <Adafruit_GFX.h>
#include <pgmspace.h>

// Font: EmojiFont12
// Source: NotoColorEmoji-Regular.ttf, size=12px, glyphs=36
// Generated by tools/font_to_header.py

namespace EmojiFont12 {

static const uint8_t PROGMEM Bitmaps[] = {
0xF8, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88,
0x88, 0xF8, 0xF8, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88,
0x88, 0x88, 0x88, 0xF8, 0xF8, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88,
0x88, 0x88, 0x88, 0x88, 0x88, 0xF8
};

typedef struct __attribute__((packed)) {
  uint16_t offset;
  uint8_t  w;
  uint8_t  h;
  int8_t   xAdvance;
  int8_t   xOffset;
  int8_t   yOffset;
} Glyph;

static const Glyph PROGMEM Glyphs[] = {
  { 0, 5, 14, 15, 0, -11 },
  { 14, 5, 14, 15, 0, -11 },
  { 28, 0, 0, 15, 0, 0 },
  { 28, 0, 0, 15, 0, 0 },
  { 28, 0, 0, 15, 0, 0 },
  { 28, 0, 0, 15, 0, 0 },
  { 28, 5, 14, 15, 0, -11 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 },
  { 42, 0, 0, 15, 0, 0 }
};

// UTF-32 codepoints for glyph indices 0..N-1
static const uint32_t PROGMEM Codepoints[] = {
  0x000A,
  0x003F,
  0x2699,
  0x26A1,
  0x2728,
  0x2B50,
  0xFE0F,
  0x1F308,
  0x1F31F,
  0x1F380,
  0x1F381,
  0x1F388,
  0x1F389,
  0x1F38A,
  0x1F3B5,
  0x1F442,
  0x1F4A1,
  0x1F4A4,
  0x1F4AD,
  0x1F4BB,
  0x1F4E2,
  0x1F4E3,
  0x1F4F1,
  0x1F50B,
  0x1F514,
  0x1F525,
  0x1F527,
  0x1F60A,
  0x1F620,
  0x1F622,
  0x1F62A,
  0x1F634,
  0x1F6E0,
  0x1F914,
  0x1F916,
  0x1F917
};

static const uint8_t  YAdvance = 14;
static const int8_t   Ascent   = 12;
static const int8_t   Descent  = 3;

// Linear search; for bigger sets, generate a binary search.
static int16_t findGlyph(uint32_t cp) {
  uint16_t n = sizeof(Codepoints)/sizeof(Codepoints[0]);
  for (uint16_t i=0;i<n;i++) {
    if (cp == pgm_read_dword(&Codepoints[i])) return (int16_t)i;
  }
  return -1;
}

// Decode next UTF-8 codepoint; returns codepoint, advances index by reference.
static uint32_t decodeUTF8(const char* s, int &i) {
  uint8_t c = (uint8_t)s[i++];
  if (c < 0x80) return c;
  if ((c & 0xE0) == 0xC0) {
    uint32_t c2 = (uint8_t)s[i++];
    return ((c & 0x1F) << 6) | (c2 & 0x3F);
  }
  if ((c & 0xF0) == 0xE0) {
    uint32_t c2 = (uint8_t)s[i++];
    uint32_t c3 = (uint8_t)s[i++];
    return ((c & 0x0F) << 12) | ((c2 & 0x3F) << 6) | (c3 & 0x3F);
  }
  if ((c & 0xF8) == 0xF0) {
    uint32_t c2 = (uint8_t)s[i++];
    uint32_t c3 = (uint8_t)s[i++];
    uint32_t c4 = (uint8_t)s[i++];
    return ((c & 0x07) << 18) | ((c2 & 0x3F) << 12) | ((c3 & 0x3F) << 6) | (c4 & 0x3F);
  }
  return 0x3F; // fallback '?'
}

// Draw a UTF-8 string at baseline (x,y)
static void drawTextUTF8(Adafruit_GFX &d, int16_t x, int16_t y, const char* utf8, uint16_t color=1) {
  for (int i=0; utf8[i];) {
    uint32_t cp = decodeUTF8(utf8, i);
    int16_t gi = findGlyph(cp);
    if (gi < 0) gi = findGlyph(0x3F); // '?'
    uint16_t off = pgm_read_word(&Glyphs[gi].offset);
    uint8_t  gw  = pgm_read_byte(&Glyphs[gi].w);
    uint8_t  gh  = pgm_read_byte(&Glyphs[gi].h);
    int8_t   xa  = pgm_read_byte(&Glyphs[gi].xAdvance);
    int8_t   xo  = pgm_read_byte(&Glyphs[gi].xOffset);
    int8_t   yo  = pgm_read_byte(&Glyphs[gi].yOffset);
    if (gw && gh) {
      d.drawBitmap(x + xo, y + yo, Bitmaps + off, gw, gh, color);
    }
    x += xa;
  }
}

} // namespace EmojiFont12
