#!/usr/bin/env python3
"""
PNG → C++ header icon converter for Adafruit_GFX drawBitmap()

- Loads PNG icons (any size), resizes to target (default 12x12)
- Converts to 1-bit, packs row-major, MSB-first, padded to full bytes per row
- Writes PROGMEM uint8_t arrays into a single header

Usage (Windows CMD):
  python tools\png_to_header.py --in assets\icons --out icon\icons_auto.h --w 12 --h 12

Requires: Pillow
  pip install pillow
"""
import argparse
import os
import sys
from pathlib import Path
from PIL import Image


def sanitize_name(name: str) -> str:
    base = ''.join(c if c.isalnum() else '_' for c in name)
    base = base.upper().strip('_')
    if not base:
        base = 'ICON'
    return base


def image_to_bitmap_bytes(img: Image.Image, width: int, height: int, threshold: int, invert: bool) -> bytes:
    # Resize
    img = img.convert('L').resize((width, height), resample=Image.NEAREST)
    # Threshold to 1-bit
    pixels = img.load()
    rows = []
    bytes_per_row = (width + 7) // 8
    for y in range(height):
        row_bytes = bytearray(bytes_per_row)
        byte_val = 0
        bit_idx = 7
        byte_pos = 0
        for x in range(width):
            lum = pixels[x, y]
            on = (lum < threshold)
            if invert:
                on = not on
            if on:
                byte_val |= (1 << bit_idx)
            bit_idx -= 1
            if bit_idx < 0:
                row_bytes[byte_pos] = byte_val
                byte_pos += 1
                byte_val = 0
                bit_idx = 7
        if bit_idx != 7:  # flush last partial byte
            row_bytes[byte_pos] = byte_val
        rows.append(bytes(row_bytes))
    return b''.join(rows)


def write_header(out_path: Path, entries: list, guard: str):
    with open(out_path, 'w', newline='\n') as f:
        f.write('// Auto-generated by tools/png_to_header.py\n')
        f.write(f'#ifndef {guard}\n')
        f.write(f'#define {guard}\n\n')
        f.write('#include <Arduino.h>\n\n')
        for name, width, height, data in entries:
            array_name = f'ICON_{sanitize_name(name)}_{width}'
            f.write(f'const uint8_t PROGMEM {array_name}[] = {{\n')
            bpr = (width + 7)//8
            idx = 0
            for y in range(height):
                f.write('  ')
                for x in range(bpr):
                    val = data[idx]
                    f.write(f'0x{val:02X}')
                    idx += 1
                    if not (y == height-1 and x == bpr-1):
                        f.write(', ')
                f.write('\n')
            f.write('};\n\n')
        f.write(f'#endif // {guard}\n')


def main():
    ap = argparse.ArgumentParser(description='Convert PNG icons to C++ PROGMEM bitmaps')
    ap.add_argument('--in', dest='inp', required=True, help='Input file or directory of PNGs')
    ap.add_argument('--out', dest='out', required=True, help='Output header path (e.g., icon/icons_auto.h)')
    ap.add_argument('--w', dest='width', type=int, default=12, help='Target width (default 12)')
    ap.add_argument('--h', dest='height', type=int, default=12, help='Target height (default 12)')
    ap.add_argument('--threshold', type=int, default=128, help='Luminance threshold 0-255 (default 128)')
    ap.add_argument('--invert', action='store_true', help='Invert ON/OFF after threshold')
    args = ap.parse_args()

    inp = Path(args.inp)
    out = Path(args.out)
    width = args.width
    height = args.height
    threshold = max(0, min(255, args.threshold))
    invert = args.invert

    files = []
    if inp.is_dir():
        files = sorted([p for p in inp.iterdir() if p.suffix.lower() == '.png'])
    elif inp.is_file():
        files = [inp]
    else:
        print('Input path not found:', inp, file=sys.stderr)
        sys.exit(1)

    if not files:
        print('No PNG files found', file=sys.stderr)
        sys.exit(1)

    out.parent.mkdir(parents=True, exist_ok=True)
    entries = []
    for p in files:
        try:
            im = Image.open(p)
        except Exception as e:
            print(f'Skip {p.name}: {e}', file=sys.stderr)
            continue
        data = image_to_bitmap_bytes(im, width, height, threshold, invert)
        entries.append((p.stem, width, height, data))

    guard = sanitize_name(out.stem) + '_H'
    write_header(out, entries, guard)
    print(f'Wrote {out} with {len(entries)} icons ({width}x{height})')


if __name__ == '__main__':
    main()


